### PR TITLE
Improve URL matching regex

### PR DESCRIPTION
**Pull request by boblehest**
Made some minor changes that should be spec compliant (to [RFC 1738](https://www.ietf.org/rfc/rfc1738.txt)). The thing that confused me the most (in `url_regex.hh`) was `host` being optional, is there a good reason for that?

Somewhat relevant issue: #155

### CODE REVIEW

**Comment by jelly** [comment]
The optional host is nack, this will make file:///tmp/foo/bar.html fail.

**Comment by jelly** [comment]
I'm not sure about the password related changes it all seems to work fine without these changes for me.

**Comment by boblehest** [comment]
Yeah, I figured it might be for file:// URLs some time after creating this PR. :/

It seemed to work fine for me too, until it didn't, so I made it more correct. (Except for the host part :))

**Comment by jelly** [comment]
Please drop the optional host commit, rebase it and I'll merge it.

**Comment by boblehest** [comment]
I've dropped the "required host" commit, and force pushed to the same branch, hoping that it doesn't break things here on github. :)

**Comment by jelly** [comment]
Manually applied.

**Pull request closed without merging**
