### PR TITLE
Add 'term' config option

### PR DESCRIPTION
**Pull request by jflombera**
Option to override the default TERM set by termite.

### CODE REVIEW

**Comment by thestinger** [comment]
I don't want to support this. Using another value for `TERM` is broken. If there are any issues with the terminfo file that's currently used (which was based on vte-256color from ncurses, and may not be entirely correct) then those issues should be fixed.

**Comment by thestinger** [comment]
If you're logging in to another computer, you should install the terminfo file there with `tic`. Even if that wasn't an option, you wouldn't want an incorrect value locally to work around a problem on one server. The workaround belongs there if you really must do it, but you should just install the terminfo file (don't need to be root).

**Comment by jflombera** [comment]
@thestinger , thank you for your prompt reply.

I usually have to connect to different remote machines and not all of them are Linux (AIX, HPUX, Solaris).  I don't own those machines nor am allowed to install anything in them.  Sometimes I just need to check some system information (e.g. top) or change some configurations (e.g. vim) and never login into that machine again.

For these reasons, installing the terminfo in the remote machines is not an option for me.  TERM=xterm-256color is a much safer value for me.

This option would allow users in situations like mine to workaround for these limitations.

Would you reconsider it if we explicitly state in the documentation that this option is for the convenience of the user only and no value other than xterm-termite is officially supported?

I am not really familiar with termite's code nor terminfo, so the following question is out of ignorance and for informative purposes only, why was necessary to create a new terminfo (xterm-termite) and what makes it different?

**Comment by thestinger** [comment]
Installing the terminfo file with tic places it in your home directory. I can't think of a situation where you would be unable to create dotfiles in your home directory. The xterm-256color terminfo has the wrong values, so programs relying on terminfo are not going to work properly. I'm not going to support the option of a hack that's never the right choice. Even if you want a broken workaround for some machines, you shouldn't break it on machines where you *do* have the terminfo file, such as locally. It's the wrong approach.

**Comment by jflombera** [comment]
Ok.  Thank you for your time.

**Pull request closed without merging**
