### PR TITLE
rebased PR #75

### PR DESCRIPTION
**Pull request by holomorph**
rebased #75 and added mention in the manual

### CODE REVIEW

**Comment by polyzen** [comment]
Sorry if this is a stupid question, but couldn't you have just rebased your branch in #74 and pushed to your github fork?

**Comment by holomorph** [comment]
@thestinger @vodik ping

**Comment by thestinger** [comment]
Thanks, sorry for taking so long to get to this.

**Comment by holomorph** [comment]
Thank you

**Pull request merged**
