### PR TITLE
Change font with Ctrl + _

### PR DESCRIPTION
**Pull request by juchiast**
In config file, split fonts with `,` :

```
font = Fixed 10, Source Code Pro Medium 10
```

After that, we can change font with Crtl + _

### CODE REVIEW

**Comment by jelly** [comment]
What's the difference between defining the font comma separated and as the font size is configured currently?

The font size can also already be changed with Ctrl shift + and Ctrl  -

**Comment by jelly** [comment]
Or is this to change between fixed and proportional sized fonts?

**Comment by juchiast** [comment]
You can change switch between different fonts like DejaVu, Monospace, Source code pro, etc.

**Comment by jelly** [comment]
I don't see a use-case for selecting different fonts with a keybinding. Different fonts require multiple configs.

**Comment by thestinger** [comment]
What is the point of switching between fonts though?

**Comment by juchiast** [comment]
I implemented this feature because I use the default monospace font while doing regular tasks (`Fixed 10` font, it's not space consuming), but when I code in vim, I need a better font for coding (e.g. Source Code Pro).

**Pull request closed without merging**
