### PR TITLE
add 'decorated' config option to disable csd

### PR DESCRIPTION
**Pull request by colemickens**
This adds a new config option so that tiling window manager users can use termite without decorations.

### CODE REVIEW

**Comment by thestinger** [comment]
It already has no decorations when the window manager is setting window hints properly. I don't want to expose configuration to work around bugs.

**Comment by thestinger** [comment]
I use Termite in i3 and there are no client-side window decorations. That also applies to all other GTK3 applications. A window manager unable to handle this properly has the same problem for all other GTK3 applications.

**Comment by colemickens** [comment]
I don't know that such a hinting mechanism exists in Wayland yet. This is the only way I've managed to achieve Termite without decorations under Sway or Orbment. That having been said, I understand why this patch may not be accepted. Thanks for looking!

**Comment by thestinger** [comment]
Ah, I didn't realize it was about Wayland.

**Comment by fdietze** [comment]
I can confirm that this works well and makes termite more usable in wayland. Please merge.

**Comment by thestinger** [comment]
I don't think implementing this for each application is the right way to go. It should be addressed elsewhere. That's why it hasn't been merged. I think an attempt should be made to figure out how to fix it properly and get that upstream before adding another hack in Termite.

**Comment by Earnestly** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/gtk3-make-csd-optional.patch?h=gtk3-optional-csd

**Comment by aroig** [comment]
Well, regarding the whole client-side decorations mess:

* GTK upstream believe they should not be disabled. The reason is that once applications start using the decorations to convey content, removing them cripples the application.

* There is a recent long and convoluted [thread](https://lists.freedesktop.org/archives/wayland-devel/2016-March/027655.html) on wayland-devel started by sway's main developer, regarding prospects of standardization for several things of interest to users of lightweight window managers. This involved some discussion on client-side decorations.

* On X, client-side decorations can be disabled, and fall back to the window-manager handling the decorations. Then the wm can decide whether to render them or not. On wayland there is no fallback, and the client is always responsible for its decorations. And this most probably will not change.

* One solution would be a mechanism where the window-manager hints the client whether to render or not the decorations, but the client would have the last word on it. This was discussed on the above thread, but I am not certain at all it will be implemented from what I read there.

The end result of the current state of affairs, is that decorations are a responsibility of the applications.

At some point there may be a wayland protocol for the application to decide what to do based on hints of the window-manager. That would involve the application actively deciding not to render them.

So, in the meantime, applications concerned themselves about light-weight window manager usage, might as well implement their own mechanism to not render decorations. It is a one-liner after all.

The whole thing sucks.

**Comment by Earnestly** [comment]
See above linked patch, removing a few `#ifdefs` makes CSD just as optional as seen on X11 via an already exposed `GTK_CSD` environment variable.

**Comment by aroig** [comment]
I've seen it. I'm pretty sure anything like this will not be merged in gtk upstream though.

By the way, How does this distinguish which CSD's to remove and which not?

**Comment by Earnestly** [comment]
Don't confuse CSD and the header bar widget, two different things.

**Comment by jelly** [comment]
Superseeded by this one https://github.com/thestinger/termite/pull/434/files

**Comment by thestinger** [comment]
https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=f2adaba237519642b88ccb42b47a95cf539a2a12

**Pull request closed without merging**
