### PR TITLE
Add ctrl-shift-a for selecting all text

### PR DESCRIPTION
**Pull request by 0xItx**
Somewhat quicker than selection mode for when you wish to select very large amounts of text (for copying to the clipboard or otherwise).
Other terminals (gnome-terminal, xfce4-terminal, ...) use an identical key-binding.

### CODE REVIEW

**Comment by 0xItx** [comment]
@thestinger - are you willing to merge this?
If not, I'll close the PR.

**Comment by thestinger** [comment]
I might be, I just don't really know if I want it at the moment.

**Comment by wsdjeg** [comment]
make sure this hotkey will not break other apps, such as neovim or vim or irssi, and so on.

**Comment by 0xItx** [comment]
@wsdjeg - it's {neovim, irssi, tmux, minicom, *-ncurses} friendly.
I doubt there'll be any clashes with common programs since other terminals implement this very same key-binding as well.

**Comment by wsdjeg** [comment]
I know ,such as gnome-terminal, but by default only `ctrl+shift+c` and `ctrl+shilf+v` are enabled, and I also disable all other hotkeys. because all other hotkeys I need to use them in vim or other app.
BTW, I use termite in i3wm, so I has no gui to set the option of termite, only one config file `~/.config/termite/config`.so I think I could be able disable some hotkeys via the config file.

**Review by kyrias — COMMENTED** [review]
This does not belong in this PR.

**Comment by kyrias** [comment]
I'm in favor of it, but the `ctrl-super-a` commit does not belong in this PR.

**Review by jelly — CHANGES_REQUESTED** [review]
The ctrl+shift+ does no belong in the PR. Also please rebase the change.

**Comment by 0xItx** [comment]
@kyrias @jelly - yeah, that `ctrl-shift-` commit shouldn't have gone to my `master`, sorry for that.

I removed it & rebased the change.

**Comment by wsdjeg** [comment]
I use <ctrl shift a> to call a func in vim,if it is merged will it break the user's hotkey?

**Comment by kyrias** [comment]
You bind the super key in vim?  That is highly unlikely...

**Comment by wsdjeg** [comment]
@kyrias I use neovim instead of vim, so most of my work is in neovim. I need all the functional key. such as `super` `alt` `ctrl` and so on. as I know vim has a lot of bugs about mappings of `alt`.

**Comment by kyrias** [comment]
How exactly are you binding it?  Didn't know that termite passed it through.

**Comment by jelly** [comment]
@thestinger do we still want this?

**Comment by jelly** [comment]
Just tested it and it feels very buggy. For me it "inverts" the colors (to select text) and then I still have to press enter to get rid of the selection.

Second issue is that it also selects blank lines below the last $ (prompt entry)

Both are probably upstream (vte3) issues.

**Comment by Radivarig** [comment]
Just to mention the selection-mode way to select all:
- `ctrl+shift+space` (enter selection-mode)
- `v` (enter visual-mode)
- `g` (go to start of first line)

**Comment by thestinger** [comment]
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.

**Pull request closed without merging**
