### PR TITLE
Add option to allow execution of a program with arguments without use of shell quotes

### PR DESCRIPTION
**Pull request by MachFour**

### CODE REVIEW

**Comment by thestinger** [comment]
I don't think this is the right way to approach this. There should be one way to run commands. It would make sense to treat regular arguments as commands and have people use `--` in the default way to pass switches to those commands. If that was going to be done, the `-e` switch should also be removed. I'm not necessarily saying I want that, but I would be open to it (but not to this).

**Comment by MachFour** [comment]
I was actually going to suggest removing `-e`, since this feature makes `-e` unnecessary. Regarding the `--` usage, it seems consistent with the idea of 'marking the end of options', as used in e.g.  `xinit -- /usr/X11R6/bin/Xqdss :1`*  so I don't think it is a serious abuse of the option. But obviously it's your call.

Or are you suggesting that we pass the program path with `-e` and the arguments to that program after `--` ?

*(from http://www.x.org/archive/X11R6.8.2/doc/xinit.1.html)

**Comment by thestinger** [comment]
No, I'm suggesting that you remove `-e` completely, while leaving the standard `--` behavior intact.

**Comment by MachFour** [comment]
Can you give me an example of how you envisage the `--` option working with termite? I'll try and implement that

**Comment by thestinger** [comment]
The way it already works by default in all GNU / GTK+ programs. It ends command-line option parsing. No changes are required.

**Comment by thestinger** [comment]
I'm suggesting replacing `-e` with passing the command as a set of regular arguments, not as parameters to a command-line switch breaking the standard GNU option parsing paradigm.

**Comment by MachFour** [comment]
I'm having trouble understanding why this use of `--` is breaking the standard paradiagm. I do want to end option parsing with `--`, since the rest of termite's arguments become the argv of the executed program. If I want to do something like `termite -- vim -c 'colorscheme delek'`, I don't want termite interpreting the `-c` as its config file. If it were changed to something like `termite -x vim -c 'colorscheme delek'`, you'd have to do all this messing around with the GOption parser to make it work, because the `--` functionality is already built in.

By way of comparison, would you say that the usage of `--` as in startx is equally inappropriate, or if not, could you explain what the difference is?

**Comment by MachFour** [comment]
for reference, from http://unix.stackexchange.com/questions/147143/when-and-how-was-the-double-dash-introduced-as-an-end-of-options-delimiter:

> But it wasn't until POSIX.2 (1992) that the Utility Syntax Guidelines were adopted, which contain the famous Guideline 10:
> `Guideline 10:    The argument "--" should be accepted as a delimiter
                 indicating the end of options.  Any following
                 arguments should be treated as operands, even if they
                 begin with the '-' character.  The "--" argument
                 should not be used as an option or as an operand.`

**Comment by thestinger** [comment]
Ending option parsing is what `--` already does by default. You're changing how it works.

**Comment by thestinger** [comment]
The way `startx` uses it isn't the standard way. The standard way is already supported in Termite since the GNU / GTK+ option parsing libraries already implement it. It just doesn't take any regular arguments right now... but it could.

**Comment by MachFour** [comment]
I actually did use the GNU/GTK+ option parsing library to achieve this. It was really easy and elegant, which is why I'm surprised that it's the wrong way to use this functionality of the option parser. (All I really had to do was add one line to the `GOptionEntry entries[]` table). I would never reimplement something if the library provided an simple way of doing it already.

**Comment by thestinger** [comment]
It already handles `--` by default in the proper way, and I'm not open to changing it. I'm not interested in arguing about this. I'm open to doing it the way I think is sane, but I have limited time to devote to Termite and I'm not entirely sure if I want to change it.

**Comment by thestinger** [comment]
I'm not saying that the problem is duplicated code. The problem is changing how `--` works when it's unnecessary. The option parsing library already has the standard handling for it by default. There is nothing to change if you implement it how I suggested (pass regular arguments as the command).

**Comment by MachFour** [comment]
I'm happy to implement it the way you would prefer. I just don't know exactly what you mean. Can you please give me an example command line?

**Comment by thestinger** [comment]
`termite htop`, `termite -- htop -C`, `termite htop -- -C` (i.e. the standard way of using `--` to halt option parsing, which doesn't require any code since it's already present)

**Comment by MachFour** [comment]
So in the second case, is the argv of the child process `htop -C` or does termite execute the default shell? And in the third case, is the argv `htop` or is it `htop -- -C` (so that htop ignores -C)?

**Comment by MachFour** [comment]
I think what you're getting at is you want the `--` to be transparently passed down to the child process, is that it?

**Comment by thestinger** [comment]
The child process would be `htop -C` in the second and third case. There's no special handling of `--` required in Termite for that. It just needs to use the remaining arguments after option parsing as the command. No special handling.

**Comment by thestinger** [comment]
I don't want `--` to be special. I want the standard behavior used by other programs.

**Comment by MachFour** [comment]
Funnily enough, my patch does this already. You don't even have to use `--`

**Comment by thestinger** [comment]
No, that's not what I'm saying.

**Comment by MachFour** [comment]
I am pretty sure I have (unintentionally) implemented this in the way that you wanted, because I misunderstood the library functionality. I used G_OPTION_REMAINING to collect the unparsed arguments, which I thought required specifying `--` on the command line so as not to cause an error. But it turns out you don't need to do this, which is why the examples you gave all work as intended.

So in summary, if there are any unparsed arguments, then they become the command_argv for vte to spawn.

If this isn't the way you wanted it, then I'm really confused.

**Comment by thestinger** [comment]
Ah, well then it might be doing what I want, but I don't think it needs to use `G_OPTION_REMAINING`. It's well-defined to simply use `argc` and `argv` after passing them to the option parser. It reshuffles them to remove the options it parses. That's why it takes `argv` by reference.

**Comment by MachFour** [comment]
from https://developer.gnome.org/glib/stable/glib-Commandline-option-parser.html#G-OPTION-REMAINING:CAPS:

> Using G_OPTION_REMAINING instead of simply scanning argv for leftover arguments has the advantage that GOption takes care of necessary encoding conversions for strings or filenames.

**Comment by MachFour** [comment]
By the way, I made a new pull request, with the (now) confusing commit messages and description removed

**Pull request closed without merging**
