### PR TITLE
Fix clear scrollback issue

### PR DESCRIPTION
**Pull request by ryancarins**

### CODE REVIEW

**Comment by jelly** [comment]
What's the rationale behind this change?

**Comment by ryancarins** [comment]
@jelly If you mean the change of 2j to 3j it's so that the scrollback buffer is cleared as well as the screen. If you mean the change in general it is to fix an issue that is flagged as a bug where clear doesn't clear the scrollback buffer completely.

**Comment by ifohancroft** [comment]
Will this get merged or has it been fixed in the source?

**Comment by ifohancroft** [comment]
For me, there is a bug when using 3j, that it does clear the scrollback but not the current screen.

**Comment by ifohancroft** [comment]
I am starting to think that 'clear' should stay as it is. I see how it useful to have both 'clear' and 'clear scrollback and reset' as sometimes you may want to clear the output but be able to scrollback to it and sometimes you may want to totally get rid of the output. What do you think? I will be closing my issue about it.

**Pull request closed without merging**
